USE `lorem_food_app`;
INSERT INTO `menu_item` 
VALUES (19,false,"Indian dish made from chunks of paneer/ chhena marinated in spices and grilled in a tandoor.",
"APPETIZER","Paneer Tikka",300,4.5,true,1,"https://www.cookwithkushi.com/wp-content/uploads/2023/02/tandoori_paneer_tikka_restaurant_style.jpg"),
(20,true,"Rava dosa is a South Indian breakfast made with semolina, cumin, ginger, coriander leaves and green chilies.",
"MAINCOURSE","Rava Dosa",75,3.5,true,1,"https://www.vegrecipesofindia.com/wp-content/uploads/2018/09/rava-dosa-recipe-1.jpg"),
(21,false,"Tomato soup is a soup with tomatoes as the primary ingredient.",
"SOUP","Tomato soup",180,4.8,true,1,"https://www.seriouseats.com/thmb/Gi-6GV26JfSSlqhWSCNgOGL1bAc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/15-minute-creamy-tomato-soup-vegan-recipe-hero-01_1-19875e4289354e5c981c96189f707c62.JPG"),
(22,false,"Chicken Gravy is a delicious gravy made by cooking chicken with onion & tomato cashew puree, tempered spices and masala powders.",
"GRAVY","Chicken Gravy",150,3.8,false,2,"https://www.yummytummyaarthi.com/wp-content/uploads/2016/01/1-19.jpg"),
(23,false,"Mutton biryani is a delicious dish made of meat, spices, herbs & yogurt.",
"MAINCOURSE","Mutton Biriyani",400,4.1,false,2,"https://www.cubesnjuliennes.com/wp-content/uploads/2021/03/Best-Mutton-Biryani-Recipe.jpg"),
(24,false,"Badam Milk is an Indian milk beverage flavored with ground almonds, cardamom & saffron.",
"BEVERAGE","Badam Milk",100,4.0,true,2,"https://www.funfoodfrolic.com/wp-content/uploads/2021/11/Blog-Thumbnail-300x300.jpg"),
(25,true,"Neer dosa are soft, thin, light and lacy crepes made with a finely ground batter of rice, water and salt.",
"MAINCOURSE","Neer dosa with veg curry",80,4.7,true,3,"https://imagevars.gulfnews.com/2022/01/06/Neer-dosas-are-often-accompanied-with-some-non-vegetarian-options--like-chicken-or-fish-curry--or-a-coconut-chutney_17e2dda8e6e_original-ratio.jpg"),
(26,true,"Green tea is a type of tea that is made from Camellia sinensis leaves and buds that have not undergone the same withering and oxidation process which is used to make oolong teas and black teas. ",
"BEVERAGE","Green Tea",40,4.2,true,3,"https://static-bebeautiful-in.unileverservices.com/green-tea-youthful-skin-secret_1.jpg"),
(27,false,"Strips of crispy fried chicken tossed in a spicy red chili sauce with buttery, sweet crunchy cashews and stir fried veggies (usually bell peppers).",
"APPETIZER","Dragon Chicken",350,4.4,false,3,"https://aromaticessence.co/wp-content/uploads/2022/04/dragon_chicken_dry_version_featured.jpg"),
(28,false,"Masala coated fish pieces coated well from both sides with rice flour and suji mixture is fried in oil.",
"APPETIZER","Anjal Rava Fry",650,4.9,false,4,"https://kitchenfables.com/wp-content/uploads/2016/06/rawa-fish-fry.1024x1024.png"),
(29,false,"Stir fried dish turns plain white rice into flavourful grains lightly seasoned with soy sauce and tossed with Prawns.",
"MAINCOURSE","Prawn Fried Rice",300,4.3,false,4,"https://mymorningmocha.com/wp-content/uploads/2021/11/Prawn-fried-rice-in-round-bowl.jpg"),
(30,false,"
Manchow soup - Wikipedia
It is a dark brown soup prepared with various vegetables, scallions, and chicken, thickened with broth and corn flour, and flavored with generous doses of soy sauce, salt, garlic, chili peppers and, predominantly, ginger.",
"SOUP","Chicken Manchow Soup",250,3.8,false,4,"https://cdn.shopify.com/s/files/1/0415/0460/4309/products/chickenmanchowsoup_600x600.jpg?v=1606662374"),
(31,true,"A dish, originating from the Indian subcontinent, of puri (deep-fried rounds of flour) and aloo (potato) bhaji (a spiced potato dish which may be dry or curried).",
"MAINCOURSE","Poori Bhaji",60,3.9,true,5,"https://www.spiceupthecurry.com/wp-content/uploads/2019/06/poori-bhaji-recipe-12.jpg"),
(32,false,"A rich & creamy curry made with paneer, spices, onions, tomatoes, cashews and butter.",
"GRAVY","Paneer Butter Masala",225,4.8,true,5,"https://www.vegrecipesofindia.com/wp-content/uploads/2020/01/paneer-butter-masala-1.jpg"),
(33,true,"Black tea is a type of tea that is more oxidized than oolong, yellow, white and green teas.",
"BEVERAGE","Black Tea",30,4.0,true,5,"https://www.12taste.com/in/wp-content/uploads/2022/01/middle-east-black-tea-2021-08-27-12-00-46-utc-scaled.jpg"),
(34,false,"A deliciously creamy Oreo milkshake made by blending milk, ice cream, and cookies together for a pleasing chilled drink",
"BEVERAGE","Oreo Milkshake",150,4.2,true,6,"https://bellyfull.net/wp-content/uploads/2020/07/Oreo-Milkshake-blog-3.jpg"),
(35,false,"Cooked with spicy schezwan sauce, whereas the Hakka noodle is usually made with soy sauce.",
"MAINCOURSE","Veg Schezwan Noodles",200,4.6,true,6,"https://www.nestleprofessional.in/sites/default/files/2022-05/Schezwan-Noodles_0.jpg"),
(36,false,"Manchow Soup is a restaurant style Chinese vegetarian soup made with mixed vegetables, garlic, ginger, soya sauce and ground pepper",
"SOUP","Veg Manchow Soup",200,4.5,true,6,"https://ranveerbrar.com/wp-content/uploads/2021/02/Manchow-soup_Fotor-scaled.jpg");

