USE `lorem_food_app`;
INSERT INTO `menu_item` 
VALUES (1,false,"Paneer marinated with masala and roasted with ghee and other veggies.",
"APPETIZER","Paneer Ghee Roast",300,4.5,true,1,"https://1.bp.blogspot.com/-DkzKSR5gu8I/WCYmDdC9DzI/AAAAAAAABt4/gogG0jW9iMAOljyrlqp3w7xnaM8NHoqEgCLcB/s640/Paneer%2BGhee%2Broast.JPG"),
(2,true,"Tawa- toasted, crispy and delicious dosa, folded in with masala.",
"MAINCOURSE","Masala Dosa",75,3.5,true,1,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn9WoxT7zbrBZE0zdrIpCaG_k7AIzg0tOBDymaw34t5g&s"),
(3,false,"Originated from Tibet, Its soupy, it has lots of veggies & strands of noodles.",
"SOUP","Veg Thukpa",180,4.8,true,1,"https://thumbs.dreamstime.com/b/thukpa-tibetan-noodle-soup-selective-focus-which-originated-eastern-part-tibet-vegetable-vegetarian-famous-190535465.jpg"),
(4,false,"Buttery tomato gravy with chicken.",
"GRAVY","Butter Chicken Boneless",150,3.8,false,2,"https://media.istockphoto.com/id/1170729895/photo/indian-butter-chicken-horizontal-photo.jpg?s=612x612&w=0&k=20&c=4bZViynoVnP1HaWHIY1k5FvW-dj9DM2EOMHbKnAqYZ4="),
(5,false,"Aromatic Biriyani with grilled chicken.",
"MAINCOURSE","Grilled Chicken Biriyani",365,4.1,false,2,"https://2.bp.blogspot.com/-R6xhhRK-Cvk/WTdqMNubxZI/AAAAAAAAFmY/a-KmW65TF1Ipyc0EQDbAOffbkwUiCvvWwCLcB/s1600/IMG_4797.jpg"),
(6,false,"Extremely nutritious, creamy and delicious.",
"BEVERAGE","Butterfruit Juice",100,4.0,true,2,"https://tse4.mm.bing.net/th?id=OIP.23_NqAZGa0clJztIDbFzXAAAAA&pid=Api&P=0"),
(7,true,"Savoury rice cake with sambar, originating from South India.",
"MAINCOURSE","Idli Sambar",60,4.7,true,3,"https://4.bp.blogspot.com/-7h4QRipjXu4/U6B3cPxxOPI/AAAAAAAAJQo/nKi7zDdyilg/s1600/Idli+Sambar.JPG"),
(8,true,"Prepared with freshly boiled water and leaf buds of the tea.",
"BEVERAGE","Tea",20,4.2,true,3,"https://tse1.mm.bing.net/th?id=OIP.jYwu15--4Lk9rfTCMMeo7gHaHa&pid=Api&P=0"),
(9,false,"Made with cheese and pepper and tastes absolutely delicious.",
"APPETIZER","Chicken Cheese Pepper Sausage Fry",350,4.4,false,3,"https://tse1.mm.bing.net/th?id=OIP.ecEBSFMAye87ZlQONBWv8QHaEK&pid=Api&P=0"),
(10,false,"Pomfret fish is marinated with spices, coated with flour and is shallow fried on tava or griddle.",
"APPETIZER","Pomfret Tawa Fry",750,4.9,false,4,"https://tse1.mm.bing.net/th?id=OIP.fc7iyA1WC-j0Ln6III02WwHaE8&pid=Api&P=0"),
(11,false,"Thali consists of prawns curry with full of flavor and the fish which is fried in a certain way which you will never find anywhere else in the world.",
"MAINCOURSE","Fish Thali",400,4.3,false,4,"https://curlytales.com/wp-content/uploads/2017/07/the-fish-thali-prawn.jpg"),
(12,false,"Made by combining fish and prawns with vegetables and stock or water.",
"SOUP","Seafood Soup",400,3.8,false,4,"https://tse4.mm.bing.net/th?id=OIP.uKmnB3X7vlsoCykAJql4HgHaE8&pid=Api&P=0"),
(13,true,"Whole wheat bread with a spiced and gravy-like dish",
"MAINCOURSE","Chapathi",60,3.9,true,5,"http://sanidli.com/wp-content/uploads/2020/03/chapati-chola-1.jpg"),
(14,false,"Soft paneer cubes marinated in a seasoned masala and cooked in a tandoor.",
"GRAVY","Paneer Tikka Masala",225,4.8,true,5,"https://i1.wp.com/vegecravings.com/wp-content/uploads/2018/06/Paneer-Tikka-Masala-Recipe-Step-By-Step-Instructions.jpg?w=1612&quality=65&strip=all&ssl=1"),
(15,true,"Beverage prepared from roasted coffee beans.",
"BEVERAGE","Coffee",20,4.0,true,5,"https://tse2.mm.bing.net/th?id=OIP.xUEtOYf3IDCp6dKWs-1axQHaEo&pid=Api&P=0"),
(16,false,"Combined mangoes, milk, sugar and ice cubes in a blender and blended until it is smooth and frothy.",
"BEVERAGE","Mango Milkshake",100,4.2,true,6,"https://tse3.mm.bing.net/th?id=OIP.iPF3bpgaJn7L_TL5JzkDJQHaLH&pid=Api&P=0"),
(17,false,"Stir fried dish turns plain white rice into flavourful grains lightly seasoned with soy sauce and tossed with colouful vegetables.Served with raitha and gravy.",
"MAINCOURSE","Veg Fried Rice",200,4.6,true,6,"https://tse2.mm.bing.net/th?id=OIP.JzL2KQaClcivAwxADQTykAHaE8&pid=Api&P=0"),
(18,false,"Heated olive oil in a large saucepan, and saute onion and garlic until tender.",
"SOUP","Brocolli Onion Soup",250,4.5,true,6,"https://tse4.mm.bing.net/th?id=OIP.wo2IhVUWI1IccPk9EMcPLwHaEK&pid=Api&P=0");

