USE `lorem_food_app`;
INSERT INTO `restaurant` 
VALUES 
(1,'3rd Floor, Samanvay Boutique Hotel, Kinnimulki Main Road, near Govinda Kalyana Mantapa',
'Udupi',
'India',
'https://lh3.googleusercontent.com/p/AF1QipMoS5O1_EoubbURi-SrSRoXYqb3QqiV7Hxx1Qys=s680-w680-h510',
'Saffron Vegetarian Cuisine',
'11:00 AM',
4.1,
'Karnataka',
'OPEN',
'10:00 PM'),
(2,'Dr. U. R. RAO Complex, near Udupi Sri Krishna Matha, Thenkapetuser',
'Udupi',
'India',
'https://lh5.googleusercontent.com/p/AF1QipPXy8dcKegAhoyXxUaTIooYtAuAQHjcGMrk5mbC=w260-h175-n-k-no',
'Woodlands Restaurant',
'12:00 AM',
4.4,
'Karnataka',
'OPEN',
'11:00 PM'),
(3,'8PVX+9CC, Near City Bus Stand, First floor, Above Silk Hina, opposite Shoe Bazar',
'Udupi',
'India',
'https://lh3.googleusercontent.com/p/AF1QipNEm9r1GhQ2XV8HgaxVUo1rYf3OAl4tI61EofL5=s680-w680-h510',
'SS Family Restaurant',
'12:00 AM',
4.4,
'Karnataka',
'CLOSED',
'11:00 PM'),
(4,'4th Floor, Bharath Mall, Bejai Road Opp KSRTC Bus Stand',
'Mangaluru',
'India',
'https://lh5.googleusercontent.com/p/AF1QipONru4vgVr-GCEwLVsCXGCdFt1RPssM9vKNDXkS=w260-h175-n-k-no',
'Thyme Family Restaurant',
'12:00 AM',
4.3,
'Karnataka',
'CLOSED',
'11:00 PM'),
(5,'Door#14-3-308/7, Balmatta Rd, near Hotel Usha',
'Mangaluru',
'India',
'https://lh5.googleusercontent.com/p/AF1QipNu4Oo1oY1ljcZ_vPQtmb1Py-BAwqbaxm8XY2rL=w260-h175-n-k-no',
'SHETTY LUNCH HOME',
'11:00 AM',
4.0,
'Karnataka',
'OPEN',
'10:00 PM'),
(6,'Behind Ocean Pearl, Sharada Vidyalaya Rd, Kodailbail',
'Mangaluru',
'India',
'https://lh5.googleusercontent.com/p/AF1QipOtNRmRNgHRFc-gXjr1ZRCNcbNPhNZbT-GQ9FYG=w260-h175-n-k-no',
'Machali',
'11:00 AM',
4.4,
'Karnataka',
'CLOSED',
'10:00 PM');
